AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy Slack API Lambda from S3 using Cloudformation.
Resources:
  slackApi:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: "user-group"
        S3Key: "slack-lambda.zip"
      Handler: 'at.madlmayr.SampleLambda::handleRequest'
      Runtime: java8
      Description: "Slack API Lambda"
      MemorySize: 512
      Timeout: 15
      Role: !GetAtt LambdaExecutionRole.Arn
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: FirehoseFullAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                  - firehose:*
                  - xray:*
                  - dynamodb:DescribeStream
                  - dynamodb:GetRecords
                  - dynamodb:GetShardIterator
                  - dynamodb:ListStreams
                Resource: "*"
  RateRuleDaily:
    Type: AWS::Events::Rule
    Properties:
      Description: "Run Event every Minute"
      Name: "RateRuleDaily"
      ScheduleExpression: cron(* * * * ? *)
      State: "ENABLED"
      Targets:
        - Arn: !GetAtt
            - slackApi
            - Arn
          Id: RateRuleDailyScheduler
          #RoleArn: !GetAtt
          #  - EventsInvokeKinesisTargetRole
          #  - Arn