# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
    # specify the version you desire here
    - image: softinstigate/maven-aws:latest

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx2048m

    steps:
    - checkout
    - configureAWS

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    # Make sure we have all dependencies
    - run: mvn dependency:go-offline

    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}

    # run tests!
    - run:
        name: Maven Build and Test/JaCoDo (for Code Coverage)
        # https://stackoverflow.com/questions/53010200/maven-surefire-could-not-find-forkedbooter-class/53012553#53012553
        # command: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -Dmaven.test.failure.ignore=false
        command: mvn clean install -Dmaven.test.failure.ignore=false

commands:
  configureAWS:
    description: "Configure AWS via CLI"
    steps:
      - run: export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - run: export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - run: export AWS_DEFAULT_REGION=eu-central-1
