# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
    # specify the version you desire here
    - image: softinstigate/maven-aws:latest

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx2048m

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    # Make sure we have all dependencies
    - run: mvn dependency:go-offline

    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}

    # run tests!
    - run:
        name: Maven Build and Test/JaCoDo (for Code Coverage)
        # https://stackoverflow.com/questions/53010200/maven-surefire-could-not-find-forkedbooter-class/53012553#53012553
        # command: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -Dmaven.test.failure.ignore=false
        command: mvn clean install -Dmaven.test.failure.ignore=false

    - run: export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - run: export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - run: export AWS_DEFAULT_REGION=eu-central-1


    - run:
        name: "Create Bucket if not exist"
        command: |
            if aws s3 ls s3://jars.madlmayr.at/; then
                echo "Bucket exists"
            else
                echo "Create Bucket"
                aws s3 mb s3://jars.madlmayr.at/
            fi

    - run:
        name: "Copy JAR to S3"
        command: aws s3 cp ./target/client-lambda.jar s3://jars.madlmayr.at/client-lambda.zip

    - run:
        name: "Copy CF to S3"
        command: aws s3 cp ./cloudformation.yaml s3://jars.madlmayr.at/cloudformation.yaml

    - run:
        name: "Execute Cloudformation Template"
        command: ./create-or-update-stack.sh eu-central-1 client-api --template-url https://s3.eu-central-1.amazonaws.com/jars.madlmayr.at/cloudformation.yaml --capabilities "CAPABILITY_IAM"